#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newRBS.Models.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="p4mist_db")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertElement(Element instance);
    partial void UpdateElement(Element instance);
    partial void DeleteElement(Element instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::newRBS.Properties.Settings.Default.p4mist_dbConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Element> Elements
		{
			get
			{
				return this.GetTable<Element>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Elements")]
	public partial class Element : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ElementID;
		
		private int _LayerID;
		
		private int _MaterialID;
		
		private string _ElementName;
		
		private double _StoichiometricFactor;
		
		private double _AtomicNumber;
		
		private double _MassNumber;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnElementIDChanging(int value);
    partial void OnElementIDChanged();
    partial void OnLayerIDChanging(int value);
    partial void OnLayerIDChanged();
    partial void OnMaterialIDChanging(int value);
    partial void OnMaterialIDChanged();
    partial void OnElementNameChanging(string value);
    partial void OnElementNameChanged();
    partial void OnStoichiometricFactorChanging(double value);
    partial void OnStoichiometricFactorChanged();
    partial void OnAtomicNumberChanging(double value);
    partial void OnAtomicNumberChanged();
    partial void OnMassNumberChanging(double value);
    partial void OnMassNumberChanged();
    #endregion
		
		public Element()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElementID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ElementID
		{
			get
			{
				return this._ElementID;
			}
			set
			{
				if ((this._ElementID != value))
				{
					this.OnElementIDChanging(value);
					this.SendPropertyChanging();
					this._ElementID = value;
					this.SendPropertyChanged("ElementID");
					this.OnElementIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LayerID", DbType="Int NOT NULL")]
		public int LayerID
		{
			get
			{
				return this._LayerID;
			}
			set
			{
				if ((this._LayerID != value))
				{
					this.OnLayerIDChanging(value);
					this.SendPropertyChanging();
					this._LayerID = value;
					this.SendPropertyChanged("LayerID");
					this.OnLayerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialID", DbType="Int NOT NULL")]
		public int MaterialID
		{
			get
			{
				return this._MaterialID;
			}
			set
			{
				if ((this._MaterialID != value))
				{
					this.OnMaterialIDChanging(value);
					this.SendPropertyChanging();
					this._MaterialID = value;
					this.SendPropertyChanged("MaterialID");
					this.OnMaterialIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElementName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ElementName
		{
			get
			{
				return this._ElementName;
			}
			set
			{
				if ((this._ElementName != value))
				{
					this.OnElementNameChanging(value);
					this.SendPropertyChanging();
					this._ElementName = value;
					this.SendPropertyChanged("ElementName");
					this.OnElementNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoichiometricFactor", DbType="Float NOT NULL")]
		public double StoichiometricFactor
		{
			get
			{
				return this._StoichiometricFactor;
			}
			set
			{
				if ((this._StoichiometricFactor != value))
				{
					this.OnStoichiometricFactorChanging(value);
					this.SendPropertyChanging();
					this._StoichiometricFactor = value;
					this.SendPropertyChanged("StoichiometricFactor");
					this.OnStoichiometricFactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtomicNumber", DbType="Float NOT NULL")]
		public double AtomicNumber
		{
			get
			{
				return this._AtomicNumber;
			}
			set
			{
				if ((this._AtomicNumber != value))
				{
					this.OnAtomicNumberChanging(value);
					this.SendPropertyChanging();
					this._AtomicNumber = value;
					this.SendPropertyChanged("AtomicNumber");
					this.OnAtomicNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MassNumber", DbType="Float NOT NULL")]
		public double MassNumber
		{
			get
			{
				return this._MassNumber;
			}
			set
			{
				if ((this._MassNumber != value))
				{
					this.OnMassNumberChanging(value);
					this.SendPropertyChanging();
					this._MassNumber = value;
					this.SendPropertyChanged("MassNumber");
					this.OnMassNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
