using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using GalaSoft.MvvmLight;
using GalaSoft.MvvmLight.Ioc;
using GalaSoft.MvvmLight.Command;

namespace newRBS.Database
{
    /// <summary>
    /// Class that represents the MS SQL Server database. 
    /// </summary>
    /// <remarks>
    /// It contains tables of the types <see cref="Measurement"/>, <see cref="Sample"/>, <see cref="Material"/>, <see cref="Layer"/>, <see cref="Element"/>, <see cref="Project"/> and <see cref="Measurement_Project"/>.
    /// The code for <see cref="DatabaseDataContext"/> and the table classes is autogenerated from the MS SQL Server database to the file 'Database.designer.cs'. Additional properties and methodes for these classes are defined in 'DatabasePartialMethods.cs'.
    /// </remarks>
    public partial class DatabaseDataContext
    {       
        /// <summary>
        /// Function that can be used to load specific childs of a table class at its initialization.
        /// </summary>
        /// <remarks>
        /// This is useful if a child has to be used after the scope of <see cref="DatabaseDataContext"/> ended.
        /// </remarks>
        partial void OnCreated()
        {
            //Console.WriteLine("OnCreated");
            var dlo = new DataLoadOptions();
            dlo.LoadWith<Measurement>(c => c.Sample);
            dlo.LoadWith<Material>(c => c.Layers);
            dlo.LoadWith<Layer>(c => c.Elements);
            //this.LoadOptions = dlo;
            //this.Log = Console.Out;
        }

        /// <summary>
        /// Function that is excecuted every time a <see cref="Measurement"/> instance is added to the database and which calls <see cref="DatabaseUtils.SendMeasurementNewEvent(Measurement)"/>.
        /// </summary>
        /// <param name="measurement"><see cref="Measurement"/> that has been added to the database.</param>
        partial void InsertMeasurement(Measurement measurement)
        {
            //Console.WriteLine("DatabaseDataContext.InsertMeasurement");

            ExecuteDynamicInsert(measurement);

            int temp = measurement.Sample.SampleID;
            DatabaseUtils.SendMeasurementNewEvent(measurement);
        }

        /// <summary>
        /// Function that is excecuted every time a <see cref="Measurement"/> instance in the database is modified and which calls <see cref="DatabaseUtils.SendMeasurementUpdateEvent(Measurement)"/>.
        /// </summary>
        /// <param name="measurement"><see cref="Measurement"/> that has been modified.</param>
        partial void UpdateMeasurement(Measurement measurement)
        {
            //Console.WriteLine("DatabaseDataContext.UpdateMeasurement");

            ExecuteDynamicUpdate(measurement);

            int temp = measurement.Sample.SampleID;
            DatabaseUtils.SendMeasurementUpdateEvent(measurement);
        }

        /// <summary>
        /// Function that is excecuted every time a <see cref="Measurement"/> instance is deleted from the database and which calls <see cref="DatabaseUtils.SendMeasurementRemoveEvent(Measurement)"/>.
        /// </summary>
        /// <param name="measurement"><see cref="Measurement"/> that has been deleted from the database.</param>
        partial void DeleteMeasurement(Measurement measurement)
        {
            //Console.WriteLine("DatabaseDataContext.DeleteMeasurement");

            ExecuteDynamicDelete(measurement);

            DatabaseUtils.SendMeasurementRemoveEvent(measurement);
        }
    }

    /// <summary>
    /// Class that stores the properties of a single measurement.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Measurement"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Measurement
    {
        /// <summary>
        /// property that holds the array of the RBS counts per channel. 
        /// </summary>
        /// <remarks>
        /// Internally (in the MS SQL Server database), the data is stored as byte[]/varbinary(MAX). The 'get' and 'set' functions of this property convert the data to/from int[].
        /// Therfore, each accsess of <see cref="Measurement.SpectrumY"/> leads to reading the hole spectrum from the database. As a consequence, one should always save SpectrumY as a local variable before looping over it!
        /// </remarks>
        public int[] SpectrumY
        {
            get
            {
                if (SpectrumYByte == null)
                    Console.WriteLine("null");
                int[] intArray = new int[SpectrumYByte.Length / sizeof(int)];
                Buffer.BlockCopy(SpectrumYByte.ToArray(), 0, intArray, 0, intArray.Length * sizeof(int));
                return intArray;
            }
            set
            {
                byte[] byteArray = new byte[value.Length * sizeof(int)];
                Buffer.BlockCopy(value, 0, byteArray, 0, byteArray.Length);
                SpectrumYByte = byteArray;
            }
        }

        /// <summary>
        /// Property, which 'get' function calculates the energy values for each channel based on <see cref="Measurement.EnergyCalOffset"/> and <see cref="Measurement.EnergyCalSlope"/>.
        /// </summary>
        public float[] SpectrumXCal
        {
            get
            {
                float[] spectrumXCal = new float[NumOfChannels];
                for (int i = 0; i < NumOfChannels; i++)
                    spectrumXCal[i] = (float)EnergyCalOffset + i * (float)EnergyCalSlope;
                return spectrumXCal;
            }
        }
    }

    /// <summary>
    /// Class that stores the properties of a element in <see cref="Layer"/> of a <see cref="Material"/>.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Element"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Element{}

    /// <summary>
    /// Class that stores the properties of a layer of a <see cref="Material"/>.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Layer"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Layer { }

    /// <summary>
    /// Class that stores the properties of a material definition. <see cref="Sample"/>s can contain a reference to a <see cref="Material"/>.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Material"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Material { }

    /// <summary>
    /// Class that stores the properties of a sample. Can contain a reference to a <see cref="Material"/>.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Sample"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Sample { }

    /// <summary>
    /// Class that stores the properties of a project containing several <see cref="Measurement"/>s as defined in <see cref="Measurement_Project"/>.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Project"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Project { }

    /// <summary>
    /// Class that stores the relationship between <see cref="Measurement"/>s and <see cref="Project"/>s.
    /// </summary>
    /// <remarks>
    /// Can be saved to the MS SQL Server database via a table of <see cref="Measurement_Project"/>s in <see cref="DatabaseDataContext"/>.
    /// </remarks>
    public partial class Measurement_Project { }
}
