// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Epsara {

	using System;

	public delegate void DataMeasurementForallCallback(Epsara.DataMeasurement measurement_data);

}
