// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Epsara {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class PhyscoreOdeInputParameter : GLib.Opaque {

		public PhyscoreOdeInputParameter(IntPtr raw) : base(raw) {}

#endregion
	}
}
