<?xml version="1.0" encoding="utf-8"?><Database Name="p4mist_db" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SVRH;Initial Catalog=p4mist_db;Persist Security Info=True;User ID=p4mist" SettingsObjectName="newRBS.Properties.Settings" SettingsPropertyName="p4mist_dbConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Elements" Member="Elements">
    <Type Name="Element">
      <Column Name="ElementID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElementName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StoichiometricFactor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AtomicNumber" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MassNumber" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Material_Element" Member="Material" ThisKey="MaterialID" OtherKey="MaterialID" Type="Material" IsForeignKey="true" />
      <Association Name="Layer_Element" Member="Layer" ThisKey="LayerID" OtherKey="LayerID" Type="Layer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materials" Member="Materials">
    <Type Name="Material">
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaterialName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Material_Element" Member="Elements" ThisKey="MaterialID" OtherKey="MaterialID" Type="Element" />
      <Association Name="Material_Layer" Member="Layers" ThisKey="MaterialID" OtherKey="MaterialID" Type="Layer" />
      <Association Name="Material_Sample" Member="Samples" ThisKey="MaterialID" OtherKey="MaterialID" Type="Sample" />
    </Type>
  </Table>
  <Table Name="dbo.Layers" Member="Layers">
    <Type Name="Layer">
      <Column Name="LayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LayerIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Density" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Thickness" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Layer_Element" Member="Elements" ThisKey="LayerID" OtherKey="LayerID" Type="Element" />
      <Association Name="Material_Layer" Member="Material" ThisKey="MaterialID" OtherKey="MaterialID" Type="Material" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Samples" Member="Samples">
    <Type Name="Sample">
      <Column Name="SampleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SampleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Sample_Measurement" Member="Measurements" ThisKey="SampleID" OtherKey="SampleID" Type="Measurement" />
      <Association Name="Material_Sample" Member="Material" ThisKey="MaterialID" OtherKey="MaterialID" Type="Material" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Measurements" Member="Measurements">
    <Type Name="Measurement">
      <Column Name="MeasurementID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeasurementName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Channel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SampleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SampleRemark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Orientation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StopTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Runs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Charge" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Progress" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NumOfChannels" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpectrumY" Type="System.Byte[]" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SpectrumYCalculated" Type="System.Byte[]" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StopType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StopValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnergyCalOffset" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EnergyCalSlope" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Chamber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IncomingIonAtomicNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IncomingIonEnergy" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IncomingIonAngle" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OutcomingIonAngle" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SolidAngle" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Phi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Theta" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Sample_Measurement" Member="Sample" ThisKey="SampleID" OtherKey="SampleID" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
</Database>